import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {

  const moonData = api.example.getMoonData.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {moonData.isLoading ? (
            <div className="text-xl text-white">Loading Moon Data...</div>
          ) : (
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
              <div className="text-xl text-white p-4 rounded-xl bg-white/10 hover:bg-white/20">
                <h2 className="font-bold">Moon Phase:</h2> 
                <p>{moonData.data?.phaseName}</p>
              </div>
              <div className="text-xl text-white p-4 rounded-xl bg-white/10 hover:bg-white/20">
                <h2 className="font-bold">Date Time:</h2> 
                <p>{moonData.data?.dateTime}</p>
              </div>
              <div className="text-xl text-white p-4 rounded-xl bg-white/10 hover:bg-white/20">
                <h2 className="font-bold">Angle Units:</h2> 
                <p>{moonData.data?.angleUnits}</p>
              </div>
              <div className="text-xl text-white p-4 rounded-xl bg-white/10 hover:bg-white/20">
                <h2 className="font-bold">Phase Angle:</h2> 
                <p>{moonData.data?.phaseAngle}</p>
              </div>
              <div className="text-xl text-white p-4 rounded-xl bg-white/10 hover:bg-white/20">
                <h2 className="font-bold">Phase Age:</h2> 
                <p>{moonData.data?.phaseAge}</p>
              </div>
              <div className="text-xl text-white p-4 rounded-xl bg-white/10 hover:bg-white/20">
                <h2 className="font-bold">Phase:</h2> 
                <p>{moonData.data?.phase}</p>
              </div>
            </div>
          )}
        </div>
      </main>
    </>
  );
}
